// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package org.ebook_searching.proto;

public final class Event {
  private Event() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddBookEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.ebook_searching.proto.AddBookEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The ID of the book
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <pre>
     * The title of the book
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <pre>
     * The title of the book
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <pre>
     * The genre of the book
     * </pre>
     *
     * <code>string genre = 3;</code>
     * @return The genre.
     */
    java.lang.String getGenre();
    /**
     * <pre>
     * The genre of the book
     * </pre>
     *
     * <code>string genre = 3;</code>
     * @return The bytes for genre.
     */
    com.google.protobuf.ByteString
        getGenreBytes();

    /**
     * <pre>
     * The date the book was published
     * </pre>
     *
     * <code>.google.protobuf.Timestamp published_at = 4;</code>
     * @return Whether the publishedAt field is set.
     */
    boolean hasPublishedAt();
    /**
     * <pre>
     * The date the book was published
     * </pre>
     *
     * <code>.google.protobuf.Timestamp published_at = 4;</code>
     * @return The publishedAt.
     */
    com.google.protobuf.Timestamp getPublishedAt();
    /**
     * <pre>
     * The date the book was published
     * </pre>
     *
     * <code>.google.protobuf.Timestamp published_at = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getPublishedAtOrBuilder();

    /**
     * <pre>
     * The publisher of the book
     * </pre>
     *
     * <code>string publisher = 5;</code>
     * @return The publisher.
     */
    java.lang.String getPublisher();
    /**
     * <pre>
     * The publisher of the book
     * </pre>
     *
     * <code>string publisher = 5;</code>
     * @return The bytes for publisher.
     */
    com.google.protobuf.ByteString
        getPublisherBytes();

    /**
     * <pre>
     * The language of the book
     * </pre>
     *
     * <code>string language = 6;</code>
     * @return The language.
     */
    java.lang.String getLanguage();
    /**
     * <pre>
     * The language of the book
     * </pre>
     *
     * <code>string language = 6;</code>
     * @return The bytes for language.
     */
    com.google.protobuf.ByteString
        getLanguageBytes();

    /**
     * <pre>
     * The average ratings of the book
     * </pre>
     *
     * <code>double avg_ratings = 7;</code>
     * @return The avgRatings.
     */
    double getAvgRatings();

    /**
     * <pre>
     * The count of the ratings
     * </pre>
     *
     * <code>int64 ratings_count = 8;</code>
     * @return The ratingsCount.
     */
    long getRatingsCount();

    /**
     * <pre>
     * The IDs of the authors
     * </pre>
     *
     * <code>repeated int64 author_ids = 9;</code>
     * @return A list containing the authorIds.
     */
    java.util.List<java.lang.Long> getAuthorIdsList();
    /**
     * <pre>
     * The IDs of the authors
     * </pre>
     *
     * <code>repeated int64 author_ids = 9;</code>
     * @return The count of authorIds.
     */
    int getAuthorIdsCount();
    /**
     * <pre>
     * The IDs of the authors
     * </pre>
     *
     * <code>repeated int64 author_ids = 9;</code>
     * @param index The index of the element to return.
     * @return The authorIds at the given index.
     */
    long getAuthorIds(int index);
  }
  /**
   * <pre>
   * Book Ingestion Event message definition
   * </pre>
   *
   * Protobuf type {@code org.ebook_searching.proto.AddBookEvent}
   */
  public static final class AddBookEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.ebook_searching.proto.AddBookEvent)
      AddBookEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddBookEvent.newBuilder() to construct.
    private AddBookEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddBookEvent() {
      title_ = "";
      genre_ = "";
      publisher_ = "";
      language_ = "";
      authorIds_ = emptyLongList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AddBookEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AddBookEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              genre_ = s;
              break;
            }
            case 34: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (publishedAt_ != null) {
                subBuilder = publishedAt_.toBuilder();
              }
              publishedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(publishedAt_);
                publishedAt_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              publisher_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              language_ = s;
              break;
            }
            case 57: {

              avgRatings_ = input.readDouble();
              break;
            }
            case 64: {

              ratingsCount_ = input.readInt64();
              break;
            }
            case 72: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                authorIds_ = newLongList();
                mutable_bitField0_ |= 0x00000001;
              }
              authorIds_.addLong(input.readInt64());
              break;
            }
            case 74: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                authorIds_ = newLongList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                authorIds_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          authorIds_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ebook_searching.proto.Event.internal_static_org_ebook_searching_proto_AddBookEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ebook_searching.proto.Event.internal_static_org_ebook_searching_proto_AddBookEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ebook_searching.proto.Event.AddBookEvent.class, org.ebook_searching.proto.Event.AddBookEvent.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     * The ID of the book
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <pre>
     * The title of the book
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The title of the book
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENRE_FIELD_NUMBER = 3;
    private volatile java.lang.Object genre_;
    /**
     * <pre>
     * The genre of the book
     * </pre>
     *
     * <code>string genre = 3;</code>
     * @return The genre.
     */
    @java.lang.Override
    public java.lang.String getGenre() {
      java.lang.Object ref = genre_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        genre_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The genre of the book
     * </pre>
     *
     * <code>string genre = 3;</code>
     * @return The bytes for genre.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGenreBytes() {
      java.lang.Object ref = genre_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genre_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUBLISHED_AT_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp publishedAt_;
    /**
     * <pre>
     * The date the book was published
     * </pre>
     *
     * <code>.google.protobuf.Timestamp published_at = 4;</code>
     * @return Whether the publishedAt field is set.
     */
    @java.lang.Override
    public boolean hasPublishedAt() {
      return publishedAt_ != null;
    }
    /**
     * <pre>
     * The date the book was published
     * </pre>
     *
     * <code>.google.protobuf.Timestamp published_at = 4;</code>
     * @return The publishedAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getPublishedAt() {
      return publishedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : publishedAt_;
    }
    /**
     * <pre>
     * The date the book was published
     * </pre>
     *
     * <code>.google.protobuf.Timestamp published_at = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getPublishedAtOrBuilder() {
      return getPublishedAt();
    }

    public static final int PUBLISHER_FIELD_NUMBER = 5;
    private volatile java.lang.Object publisher_;
    /**
     * <pre>
     * The publisher of the book
     * </pre>
     *
     * <code>string publisher = 5;</code>
     * @return The publisher.
     */
    @java.lang.Override
    public java.lang.String getPublisher() {
      java.lang.Object ref = publisher_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        publisher_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The publisher of the book
     * </pre>
     *
     * <code>string publisher = 5;</code>
     * @return The bytes for publisher.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPublisherBytes() {
      java.lang.Object ref = publisher_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publisher_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANGUAGE_FIELD_NUMBER = 6;
    private volatile java.lang.Object language_;
    /**
     * <pre>
     * The language of the book
     * </pre>
     *
     * <code>string language = 6;</code>
     * @return The language.
     */
    @java.lang.Override
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        language_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The language of the book
     * </pre>
     *
     * <code>string language = 6;</code>
     * @return The bytes for language.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVG_RATINGS_FIELD_NUMBER = 7;
    private double avgRatings_;
    /**
     * <pre>
     * The average ratings of the book
     * </pre>
     *
     * <code>double avg_ratings = 7;</code>
     * @return The avgRatings.
     */
    @java.lang.Override
    public double getAvgRatings() {
      return avgRatings_;
    }

    public static final int RATINGS_COUNT_FIELD_NUMBER = 8;
    private long ratingsCount_;
    /**
     * <pre>
     * The count of the ratings
     * </pre>
     *
     * <code>int64 ratings_count = 8;</code>
     * @return The ratingsCount.
     */
    @java.lang.Override
    public long getRatingsCount() {
      return ratingsCount_;
    }

    public static final int AUTHOR_IDS_FIELD_NUMBER = 9;
    private com.google.protobuf.Internal.LongList authorIds_;
    /**
     * <pre>
     * The IDs of the authors
     * </pre>
     *
     * <code>repeated int64 author_ids = 9;</code>
     * @return A list containing the authorIds.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getAuthorIdsList() {
      return authorIds_;
    }
    /**
     * <pre>
     * The IDs of the authors
     * </pre>
     *
     * <code>repeated int64 author_ids = 9;</code>
     * @return The count of authorIds.
     */
    public int getAuthorIdsCount() {
      return authorIds_.size();
    }
    /**
     * <pre>
     * The IDs of the authors
     * </pre>
     *
     * <code>repeated int64 author_ids = 9;</code>
     * @param index The index of the element to return.
     * @return The authorIds at the given index.
     */
    public long getAuthorIds(int index) {
      return authorIds_.getLong(index);
    }
    private int authorIdsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (!getGenreBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, genre_);
      }
      if (publishedAt_ != null) {
        output.writeMessage(4, getPublishedAt());
      }
      if (!getPublisherBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, publisher_);
      }
      if (!getLanguageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, language_);
      }
      if (avgRatings_ != 0D) {
        output.writeDouble(7, avgRatings_);
      }
      if (ratingsCount_ != 0L) {
        output.writeInt64(8, ratingsCount_);
      }
      if (getAuthorIdsList().size() > 0) {
        output.writeUInt32NoTag(74);
        output.writeUInt32NoTag(authorIdsMemoizedSerializedSize);
      }
      for (int i = 0; i < authorIds_.size(); i++) {
        output.writeInt64NoTag(authorIds_.getLong(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (!getGenreBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, genre_);
      }
      if (publishedAt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPublishedAt());
      }
      if (!getPublisherBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, publisher_);
      }
      if (!getLanguageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, language_);
      }
      if (avgRatings_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, avgRatings_);
      }
      if (ratingsCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, ratingsCount_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < authorIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(authorIds_.getLong(i));
        }
        size += dataSize;
        if (!getAuthorIdsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        authorIdsMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.ebook_searching.proto.Event.AddBookEvent)) {
        return super.equals(obj);
      }
      org.ebook_searching.proto.Event.AddBookEvent other = (org.ebook_searching.proto.Event.AddBookEvent) obj;

      if (getId()
          != other.getId()) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getGenre()
          .equals(other.getGenre())) return false;
      if (hasPublishedAt() != other.hasPublishedAt()) return false;
      if (hasPublishedAt()) {
        if (!getPublishedAt()
            .equals(other.getPublishedAt())) return false;
      }
      if (!getPublisher()
          .equals(other.getPublisher())) return false;
      if (!getLanguage()
          .equals(other.getLanguage())) return false;
      if (java.lang.Double.doubleToLongBits(getAvgRatings())
          != java.lang.Double.doubleToLongBits(
              other.getAvgRatings())) return false;
      if (getRatingsCount()
          != other.getRatingsCount()) return false;
      if (!getAuthorIdsList()
          .equals(other.getAuthorIdsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + GENRE_FIELD_NUMBER;
      hash = (53 * hash) + getGenre().hashCode();
      if (hasPublishedAt()) {
        hash = (37 * hash) + PUBLISHED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getPublishedAt().hashCode();
      }
      hash = (37 * hash) + PUBLISHER_FIELD_NUMBER;
      hash = (53 * hash) + getPublisher().hashCode();
      hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + getLanguage().hashCode();
      hash = (37 * hash) + AVG_RATINGS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAvgRatings()));
      hash = (37 * hash) + RATINGS_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRatingsCount());
      if (getAuthorIdsCount() > 0) {
        hash = (37 * hash) + AUTHOR_IDS_FIELD_NUMBER;
        hash = (53 * hash) + getAuthorIdsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.ebook_searching.proto.Event.AddBookEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Book Ingestion Event message definition
     * </pre>
     *
     * Protobuf type {@code org.ebook_searching.proto.AddBookEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.ebook_searching.proto.AddBookEvent)
        org.ebook_searching.proto.Event.AddBookEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ebook_searching.proto.Event.internal_static_org_ebook_searching_proto_AddBookEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ebook_searching.proto.Event.internal_static_org_ebook_searching_proto_AddBookEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.ebook_searching.proto.Event.AddBookEvent.class, org.ebook_searching.proto.Event.AddBookEvent.Builder.class);
      }

      // Construct using org.ebook_searching.proto.Event.AddBookEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        title_ = "";

        genre_ = "";

        if (publishedAtBuilder_ == null) {
          publishedAt_ = null;
        } else {
          publishedAt_ = null;
          publishedAtBuilder_ = null;
        }
        publisher_ = "";

        language_ = "";

        avgRatings_ = 0D;

        ratingsCount_ = 0L;

        authorIds_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ebook_searching.proto.Event.internal_static_org_ebook_searching_proto_AddBookEvent_descriptor;
      }

      @java.lang.Override
      public org.ebook_searching.proto.Event.AddBookEvent getDefaultInstanceForType() {
        return org.ebook_searching.proto.Event.AddBookEvent.getDefaultInstance();
      }

      @java.lang.Override
      public org.ebook_searching.proto.Event.AddBookEvent build() {
        org.ebook_searching.proto.Event.AddBookEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.ebook_searching.proto.Event.AddBookEvent buildPartial() {
        org.ebook_searching.proto.Event.AddBookEvent result = new org.ebook_searching.proto.Event.AddBookEvent(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.title_ = title_;
        result.genre_ = genre_;
        if (publishedAtBuilder_ == null) {
          result.publishedAt_ = publishedAt_;
        } else {
          result.publishedAt_ = publishedAtBuilder_.build();
        }
        result.publisher_ = publisher_;
        result.language_ = language_;
        result.avgRatings_ = avgRatings_;
        result.ratingsCount_ = ratingsCount_;
        if (((bitField0_ & 0x00000001) != 0)) {
          authorIds_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.authorIds_ = authorIds_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ebook_searching.proto.Event.AddBookEvent) {
          return mergeFrom((org.ebook_searching.proto.Event.AddBookEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.ebook_searching.proto.Event.AddBookEvent other) {
        if (other == org.ebook_searching.proto.Event.AddBookEvent.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getGenre().isEmpty()) {
          genre_ = other.genre_;
          onChanged();
        }
        if (other.hasPublishedAt()) {
          mergePublishedAt(other.getPublishedAt());
        }
        if (!other.getPublisher().isEmpty()) {
          publisher_ = other.publisher_;
          onChanged();
        }
        if (!other.getLanguage().isEmpty()) {
          language_ = other.language_;
          onChanged();
        }
        if (other.getAvgRatings() != 0D) {
          setAvgRatings(other.getAvgRatings());
        }
        if (other.getRatingsCount() != 0L) {
          setRatingsCount(other.getRatingsCount());
        }
        if (!other.authorIds_.isEmpty()) {
          if (authorIds_.isEmpty()) {
            authorIds_ = other.authorIds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAuthorIdsIsMutable();
            authorIds_.addAll(other.authorIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.ebook_searching.proto.Event.AddBookEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.ebook_searching.proto.Event.AddBookEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <pre>
       * The ID of the book
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * The ID of the book
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The ID of the book
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <pre>
       * The title of the book
       * </pre>
       *
       * <code>string title = 2;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The title of the book
       * </pre>
       *
       * <code>string title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The title of the book
       * </pre>
       *
       * <code>string title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The title of the book
       * </pre>
       *
       * <code>string title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The title of the book
       * </pre>
       *
       * <code>string title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object genre_ = "";
      /**
       * <pre>
       * The genre of the book
       * </pre>
       *
       * <code>string genre = 3;</code>
       * @return The genre.
       */
      public java.lang.String getGenre() {
        java.lang.Object ref = genre_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          genre_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The genre of the book
       * </pre>
       *
       * <code>string genre = 3;</code>
       * @return The bytes for genre.
       */
      public com.google.protobuf.ByteString
          getGenreBytes() {
        java.lang.Object ref = genre_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          genre_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The genre of the book
       * </pre>
       *
       * <code>string genre = 3;</code>
       * @param value The genre to set.
       * @return This builder for chaining.
       */
      public Builder setGenre(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        genre_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The genre of the book
       * </pre>
       *
       * <code>string genre = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGenre() {
        
        genre_ = getDefaultInstance().getGenre();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The genre of the book
       * </pre>
       *
       * <code>string genre = 3;</code>
       * @param value The bytes for genre to set.
       * @return This builder for chaining.
       */
      public Builder setGenreBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        genre_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp publishedAt_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> publishedAtBuilder_;
      /**
       * <pre>
       * The date the book was published
       * </pre>
       *
       * <code>.google.protobuf.Timestamp published_at = 4;</code>
       * @return Whether the publishedAt field is set.
       */
      public boolean hasPublishedAt() {
        return publishedAtBuilder_ != null || publishedAt_ != null;
      }
      /**
       * <pre>
       * The date the book was published
       * </pre>
       *
       * <code>.google.protobuf.Timestamp published_at = 4;</code>
       * @return The publishedAt.
       */
      public com.google.protobuf.Timestamp getPublishedAt() {
        if (publishedAtBuilder_ == null) {
          return publishedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : publishedAt_;
        } else {
          return publishedAtBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The date the book was published
       * </pre>
       *
       * <code>.google.protobuf.Timestamp published_at = 4;</code>
       */
      public Builder setPublishedAt(com.google.protobuf.Timestamp value) {
        if (publishedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          publishedAt_ = value;
          onChanged();
        } else {
          publishedAtBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * The date the book was published
       * </pre>
       *
       * <code>.google.protobuf.Timestamp published_at = 4;</code>
       */
      public Builder setPublishedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (publishedAtBuilder_ == null) {
          publishedAt_ = builderForValue.build();
          onChanged();
        } else {
          publishedAtBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * The date the book was published
       * </pre>
       *
       * <code>.google.protobuf.Timestamp published_at = 4;</code>
       */
      public Builder mergePublishedAt(com.google.protobuf.Timestamp value) {
        if (publishedAtBuilder_ == null) {
          if (publishedAt_ != null) {
            publishedAt_ =
              com.google.protobuf.Timestamp.newBuilder(publishedAt_).mergeFrom(value).buildPartial();
          } else {
            publishedAt_ = value;
          }
          onChanged();
        } else {
          publishedAtBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * The date the book was published
       * </pre>
       *
       * <code>.google.protobuf.Timestamp published_at = 4;</code>
       */
      public Builder clearPublishedAt() {
        if (publishedAtBuilder_ == null) {
          publishedAt_ = null;
          onChanged();
        } else {
          publishedAt_ = null;
          publishedAtBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * The date the book was published
       * </pre>
       *
       * <code>.google.protobuf.Timestamp published_at = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getPublishedAtBuilder() {
        
        onChanged();
        return getPublishedAtFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The date the book was published
       * </pre>
       *
       * <code>.google.protobuf.Timestamp published_at = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getPublishedAtOrBuilder() {
        if (publishedAtBuilder_ != null) {
          return publishedAtBuilder_.getMessageOrBuilder();
        } else {
          return publishedAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : publishedAt_;
        }
      }
      /**
       * <pre>
       * The date the book was published
       * </pre>
       *
       * <code>.google.protobuf.Timestamp published_at = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getPublishedAtFieldBuilder() {
        if (publishedAtBuilder_ == null) {
          publishedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getPublishedAt(),
                  getParentForChildren(),
                  isClean());
          publishedAt_ = null;
        }
        return publishedAtBuilder_;
      }

      private java.lang.Object publisher_ = "";
      /**
       * <pre>
       * The publisher of the book
       * </pre>
       *
       * <code>string publisher = 5;</code>
       * @return The publisher.
       */
      public java.lang.String getPublisher() {
        java.lang.Object ref = publisher_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          publisher_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The publisher of the book
       * </pre>
       *
       * <code>string publisher = 5;</code>
       * @return The bytes for publisher.
       */
      public com.google.protobuf.ByteString
          getPublisherBytes() {
        java.lang.Object ref = publisher_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          publisher_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The publisher of the book
       * </pre>
       *
       * <code>string publisher = 5;</code>
       * @param value The publisher to set.
       * @return This builder for chaining.
       */
      public Builder setPublisher(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publisher_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The publisher of the book
       * </pre>
       *
       * <code>string publisher = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPublisher() {
        
        publisher_ = getDefaultInstance().getPublisher();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The publisher of the book
       * </pre>
       *
       * <code>string publisher = 5;</code>
       * @param value The bytes for publisher to set.
       * @return This builder for chaining.
       */
      public Builder setPublisherBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        publisher_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object language_ = "";
      /**
       * <pre>
       * The language of the book
       * </pre>
       *
       * <code>string language = 6;</code>
       * @return The language.
       */
      public java.lang.String getLanguage() {
        java.lang.Object ref = language_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          language_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The language of the book
       * </pre>
       *
       * <code>string language = 6;</code>
       * @return The bytes for language.
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        java.lang.Object ref = language_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          language_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The language of the book
       * </pre>
       *
       * <code>string language = 6;</code>
       * @param value The language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        language_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The language of the book
       * </pre>
       *
       * <code>string language = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLanguage() {
        
        language_ = getDefaultInstance().getLanguage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The language of the book
       * </pre>
       *
       * <code>string language = 6;</code>
       * @param value The bytes for language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        language_ = value;
        onChanged();
        return this;
      }

      private double avgRatings_ ;
      /**
       * <pre>
       * The average ratings of the book
       * </pre>
       *
       * <code>double avg_ratings = 7;</code>
       * @return The avgRatings.
       */
      @java.lang.Override
      public double getAvgRatings() {
        return avgRatings_;
      }
      /**
       * <pre>
       * The average ratings of the book
       * </pre>
       *
       * <code>double avg_ratings = 7;</code>
       * @param value The avgRatings to set.
       * @return This builder for chaining.
       */
      public Builder setAvgRatings(double value) {
        
        avgRatings_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The average ratings of the book
       * </pre>
       *
       * <code>double avg_ratings = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvgRatings() {
        
        avgRatings_ = 0D;
        onChanged();
        return this;
      }

      private long ratingsCount_ ;
      /**
       * <pre>
       * The count of the ratings
       * </pre>
       *
       * <code>int64 ratings_count = 8;</code>
       * @return The ratingsCount.
       */
      @java.lang.Override
      public long getRatingsCount() {
        return ratingsCount_;
      }
      /**
       * <pre>
       * The count of the ratings
       * </pre>
       *
       * <code>int64 ratings_count = 8;</code>
       * @param value The ratingsCount to set.
       * @return This builder for chaining.
       */
      public Builder setRatingsCount(long value) {
        
        ratingsCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The count of the ratings
       * </pre>
       *
       * <code>int64 ratings_count = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearRatingsCount() {
        
        ratingsCount_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.LongList authorIds_ = emptyLongList();
      private void ensureAuthorIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          authorIds_ = mutableCopy(authorIds_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * The IDs of the authors
       * </pre>
       *
       * <code>repeated int64 author_ids = 9;</code>
       * @return A list containing the authorIds.
       */
      public java.util.List<java.lang.Long>
          getAuthorIdsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(authorIds_) : authorIds_;
      }
      /**
       * <pre>
       * The IDs of the authors
       * </pre>
       *
       * <code>repeated int64 author_ids = 9;</code>
       * @return The count of authorIds.
       */
      public int getAuthorIdsCount() {
        return authorIds_.size();
      }
      /**
       * <pre>
       * The IDs of the authors
       * </pre>
       *
       * <code>repeated int64 author_ids = 9;</code>
       * @param index The index of the element to return.
       * @return The authorIds at the given index.
       */
      public long getAuthorIds(int index) {
        return authorIds_.getLong(index);
      }
      /**
       * <pre>
       * The IDs of the authors
       * </pre>
       *
       * <code>repeated int64 author_ids = 9;</code>
       * @param index The index to set the value at.
       * @param value The authorIds to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorIds(
          int index, long value) {
        ensureAuthorIdsIsMutable();
        authorIds_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The IDs of the authors
       * </pre>
       *
       * <code>repeated int64 author_ids = 9;</code>
       * @param value The authorIds to add.
       * @return This builder for chaining.
       */
      public Builder addAuthorIds(long value) {
        ensureAuthorIdsIsMutable();
        authorIds_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The IDs of the authors
       * </pre>
       *
       * <code>repeated int64 author_ids = 9;</code>
       * @param values The authorIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllAuthorIds(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureAuthorIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, authorIds_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The IDs of the authors
       * </pre>
       *
       * <code>repeated int64 author_ids = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorIds() {
        authorIds_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.ebook_searching.proto.AddBookEvent)
    }

    // @@protoc_insertion_point(class_scope:org.ebook_searching.proto.AddBookEvent)
    private static final org.ebook_searching.proto.Event.AddBookEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.ebook_searching.proto.Event.AddBookEvent();
    }

    public static org.ebook_searching.proto.Event.AddBookEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddBookEvent>
        PARSER = new com.google.protobuf.AbstractParser<AddBookEvent>() {
      @java.lang.Override
      public AddBookEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddBookEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddBookEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddBookEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.ebook_searching.proto.Event.AddBookEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ebook_searching_proto_AddBookEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_ebook_searching_proto_AddBookEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013event.proto\022\031org.ebook_searching.proto" +
      "\032\037google/protobuf/timestamp.proto\"\317\001\n\014Ad" +
      "dBookEvent\022\n\n\002id\030\001 \001(\003\022\r\n\005title\030\002 \001(\t\022\r\n" +
      "\005genre\030\003 \001(\t\0220\n\014published_at\030\004 \001(\0132\032.goo" +
      "gle.protobuf.Timestamp\022\021\n\tpublisher\030\005 \001(" +
      "\t\022\020\n\010language\030\006 \001(\t\022\023\n\013avg_ratings\030\007 \001(\001" +
      "\022\025\n\rratings_count\030\010 \001(\003\022\022\n\nauthor_ids\030\t " +
      "\003(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_org_ebook_searching_proto_AddBookEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_ebook_searching_proto_AddBookEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_ebook_searching_proto_AddBookEvent_descriptor,
        new java.lang.String[] { "Id", "Title", "Genre", "PublishedAt", "Publisher", "Language", "AvgRatings", "RatingsCount", "AuthorIds", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
