// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package org.ebook_searching.proto;

public final class Event {
  private Event() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddBookEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.ebook_searching.proto.AddBookEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The ID of the book
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <pre>
     * The title of the book
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <pre>
     * The title of the book
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <pre>
     * List of genres of the book
     * </pre>
     *
     * <code>repeated string genres = 3;</code>
     * @return A list containing the genres.
     */
    java.util.List<java.lang.String>
        getGenresList();
    /**
     * <pre>
     * List of genres of the book
     * </pre>
     *
     * <code>repeated string genres = 3;</code>
     * @return The count of genres.
     */
    int getGenresCount();
    /**
     * <pre>
     * List of genres of the book
     * </pre>
     *
     * <code>repeated string genres = 3;</code>
     * @param index The index of the element to return.
     * @return The genres at the given index.
     */
    java.lang.String getGenres(int index);
    /**
     * <pre>
     * List of genres of the book
     * </pre>
     *
     * <code>repeated string genres = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the genres at the given index.
     */
    com.google.protobuf.ByteString
        getGenresBytes(int index);

    /**
     * <pre>
     * The date the book was published
     * </pre>
     *
     * <code>.google.protobuf.Timestamp published_at = 4;</code>
     * @return Whether the publishedAt field is set.
     */
    boolean hasPublishedAt();
    /**
     * <pre>
     * The date the book was published
     * </pre>
     *
     * <code>.google.protobuf.Timestamp published_at = 4;</code>
     * @return The publishedAt.
     */
    com.google.protobuf.Timestamp getPublishedAt();
    /**
     * <pre>
     * The date the book was published
     * </pre>
     *
     * <code>.google.protobuf.Timestamp published_at = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getPublishedAtOrBuilder();

    /**
     * <pre>
     * The publisher of the book
     * </pre>
     *
     * <code>string publisher = 5;</code>
     * @return The publisher.
     */
    java.lang.String getPublisher();
    /**
     * <pre>
     * The publisher of the book
     * </pre>
     *
     * <code>string publisher = 5;</code>
     * @return The bytes for publisher.
     */
    com.google.protobuf.ByteString
        getPublisherBytes();

    /**
     * <pre>
     * Total pages in the book
     * </pre>
     *
     * <code>int32 total_pages = 6;</code>
     * @return The totalPages.
     */
    int getTotalPages();

    /**
     * <pre>
     * List of categories the book belongs to
     * </pre>
     *
     * <code>repeated string categories = 7;</code>
     * @return A list containing the categories.
     */
    java.util.List<java.lang.String>
        getCategoriesList();
    /**
     * <pre>
     * List of categories the book belongs to
     * </pre>
     *
     * <code>repeated string categories = 7;</code>
     * @return The count of categories.
     */
    int getCategoriesCount();
    /**
     * <pre>
     * List of categories the book belongs to
     * </pre>
     *
     * <code>repeated string categories = 7;</code>
     * @param index The index of the element to return.
     * @return The categories at the given index.
     */
    java.lang.String getCategories(int index);
    /**
     * <pre>
     * List of categories the book belongs to
     * </pre>
     *
     * <code>repeated string categories = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the categories at the given index.
     */
    com.google.protobuf.ByteString
        getCategoriesBytes(int index);

    /**
     * <pre>
     * The language of the book
     * </pre>
     *
     * <code>string language = 8;</code>
     * @return The language.
     */
    java.lang.String getLanguage();
    /**
     * <pre>
     * The language of the book
     * </pre>
     *
     * <code>string language = 8;</code>
     * @return The bytes for language.
     */
    com.google.protobuf.ByteString
        getLanguageBytes();

    /**
     * <pre>
     * The description of the book
     * </pre>
     *
     * <code>string description = 9;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <pre>
     * The description of the book
     * </pre>
     *
     * <code>string description = 9;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <pre>
     * The image of the book (Base64 or URL)
     * </pre>
     *
     * <code>string image = 10;</code>
     * @return The image.
     */
    java.lang.String getImage();
    /**
     * <pre>
     * The image of the book (Base64 or URL)
     * </pre>
     *
     * <code>string image = 10;</code>
     * @return The bytes for image.
     */
    com.google.protobuf.ByteString
        getImageBytes();

    /**
     * <pre>
     * List of author details
     * </pre>
     *
     * <code>repeated int64 authorIds = 11;</code>
     * @return A list containing the authorIds.
     */
    java.util.List<java.lang.Long> getAuthorIdsList();
    /**
     * <pre>
     * List of author details
     * </pre>
     *
     * <code>repeated int64 authorIds = 11;</code>
     * @return The count of authorIds.
     */
    int getAuthorIdsCount();
    /**
     * <pre>
     * List of author details
     * </pre>
     *
     * <code>repeated int64 authorIds = 11;</code>
     * @param index The index of the element to return.
     * @return The authorIds at the given index.
     */
    long getAuthorIds(int index);
  }
  /**
   * <pre>
   * Book Ingestion Event message definition
   * </pre>
   *
   * Protobuf type {@code org.ebook_searching.proto.AddBookEvent}
   */
  public static final class AddBookEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.ebook_searching.proto.AddBookEvent)
      AddBookEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddBookEvent.newBuilder() to construct.
    private AddBookEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddBookEvent() {
      title_ = "";
      genres_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      publisher_ = "";
      categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      language_ = "";
      description_ = "";
      image_ = "";
      authorIds_ = emptyLongList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AddBookEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AddBookEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                genres_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              genres_.add(s);
              break;
            }
            case 34: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (publishedAt_ != null) {
                subBuilder = publishedAt_.toBuilder();
              }
              publishedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(publishedAt_);
                publishedAt_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              publisher_ = s;
              break;
            }
            case 48: {

              totalPages_ = input.readInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                categories_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              categories_.add(s);
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              language_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              image_ = s;
              break;
            }
            case 88: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                authorIds_ = newLongList();
                mutable_bitField0_ |= 0x00000004;
              }
              authorIds_.addLong(input.readInt64());
              break;
            }
            case 90: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) != 0) && input.getBytesUntilLimit() > 0) {
                authorIds_ = newLongList();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                authorIds_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          genres_ = genres_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          categories_ = categories_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          authorIds_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ebook_searching.proto.Event.internal_static_org_ebook_searching_proto_AddBookEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ebook_searching.proto.Event.internal_static_org_ebook_searching_proto_AddBookEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ebook_searching.proto.Event.AddBookEvent.class, org.ebook_searching.proto.Event.AddBookEvent.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     * The ID of the book
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <pre>
     * The title of the book
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The title of the book
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENRES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList genres_;
    /**
     * <pre>
     * List of genres of the book
     * </pre>
     *
     * <code>repeated string genres = 3;</code>
     * @return A list containing the genres.
     */
    public com.google.protobuf.ProtocolStringList
        getGenresList() {
      return genres_;
    }
    /**
     * <pre>
     * List of genres of the book
     * </pre>
     *
     * <code>repeated string genres = 3;</code>
     * @return The count of genres.
     */
    public int getGenresCount() {
      return genres_.size();
    }
    /**
     * <pre>
     * List of genres of the book
     * </pre>
     *
     * <code>repeated string genres = 3;</code>
     * @param index The index of the element to return.
     * @return The genres at the given index.
     */
    public java.lang.String getGenres(int index) {
      return genres_.get(index);
    }
    /**
     * <pre>
     * List of genres of the book
     * </pre>
     *
     * <code>repeated string genres = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the genres at the given index.
     */
    public com.google.protobuf.ByteString
        getGenresBytes(int index) {
      return genres_.getByteString(index);
    }

    public static final int PUBLISHED_AT_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp publishedAt_;
    /**
     * <pre>
     * The date the book was published
     * </pre>
     *
     * <code>.google.protobuf.Timestamp published_at = 4;</code>
     * @return Whether the publishedAt field is set.
     */
    @java.lang.Override
    public boolean hasPublishedAt() {
      return publishedAt_ != null;
    }
    /**
     * <pre>
     * The date the book was published
     * </pre>
     *
     * <code>.google.protobuf.Timestamp published_at = 4;</code>
     * @return The publishedAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getPublishedAt() {
      return publishedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : publishedAt_;
    }
    /**
     * <pre>
     * The date the book was published
     * </pre>
     *
     * <code>.google.protobuf.Timestamp published_at = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getPublishedAtOrBuilder() {
      return getPublishedAt();
    }

    public static final int PUBLISHER_FIELD_NUMBER = 5;
    private volatile java.lang.Object publisher_;
    /**
     * <pre>
     * The publisher of the book
     * </pre>
     *
     * <code>string publisher = 5;</code>
     * @return The publisher.
     */
    @java.lang.Override
    public java.lang.String getPublisher() {
      java.lang.Object ref = publisher_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        publisher_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The publisher of the book
     * </pre>
     *
     * <code>string publisher = 5;</code>
     * @return The bytes for publisher.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPublisherBytes() {
      java.lang.Object ref = publisher_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publisher_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOTAL_PAGES_FIELD_NUMBER = 6;
    private int totalPages_;
    /**
     * <pre>
     * Total pages in the book
     * </pre>
     *
     * <code>int32 total_pages = 6;</code>
     * @return The totalPages.
     */
    @java.lang.Override
    public int getTotalPages() {
      return totalPages_;
    }

    public static final int CATEGORIES_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList categories_;
    /**
     * <pre>
     * List of categories the book belongs to
     * </pre>
     *
     * <code>repeated string categories = 7;</code>
     * @return A list containing the categories.
     */
    public com.google.protobuf.ProtocolStringList
        getCategoriesList() {
      return categories_;
    }
    /**
     * <pre>
     * List of categories the book belongs to
     * </pre>
     *
     * <code>repeated string categories = 7;</code>
     * @return The count of categories.
     */
    public int getCategoriesCount() {
      return categories_.size();
    }
    /**
     * <pre>
     * List of categories the book belongs to
     * </pre>
     *
     * <code>repeated string categories = 7;</code>
     * @param index The index of the element to return.
     * @return The categories at the given index.
     */
    public java.lang.String getCategories(int index) {
      return categories_.get(index);
    }
    /**
     * <pre>
     * List of categories the book belongs to
     * </pre>
     *
     * <code>repeated string categories = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the categories at the given index.
     */
    public com.google.protobuf.ByteString
        getCategoriesBytes(int index) {
      return categories_.getByteString(index);
    }

    public static final int LANGUAGE_FIELD_NUMBER = 8;
    private volatile java.lang.Object language_;
    /**
     * <pre>
     * The language of the book
     * </pre>
     *
     * <code>string language = 8;</code>
     * @return The language.
     */
    @java.lang.Override
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        language_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The language of the book
     * </pre>
     *
     * <code>string language = 8;</code>
     * @return The bytes for language.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 9;
    private volatile java.lang.Object description_;
    /**
     * <pre>
     * The description of the book
     * </pre>
     *
     * <code>string description = 9;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The description of the book
     * </pre>
     *
     * <code>string description = 9;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGE_FIELD_NUMBER = 10;
    private volatile java.lang.Object image_;
    /**
     * <pre>
     * The image of the book (Base64 or URL)
     * </pre>
     *
     * <code>string image = 10;</code>
     * @return The image.
     */
    @java.lang.Override
    public java.lang.String getImage() {
      java.lang.Object ref = image_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        image_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The image of the book (Base64 or URL)
     * </pre>
     *
     * <code>string image = 10;</code>
     * @return The bytes for image.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getImageBytes() {
      java.lang.Object ref = image_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        image_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHORIDS_FIELD_NUMBER = 11;
    private com.google.protobuf.Internal.LongList authorIds_;
    /**
     * <pre>
     * List of author details
     * </pre>
     *
     * <code>repeated int64 authorIds = 11;</code>
     * @return A list containing the authorIds.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getAuthorIdsList() {
      return authorIds_;
    }
    /**
     * <pre>
     * List of author details
     * </pre>
     *
     * <code>repeated int64 authorIds = 11;</code>
     * @return The count of authorIds.
     */
    public int getAuthorIdsCount() {
      return authorIds_.size();
    }
    /**
     * <pre>
     * List of author details
     * </pre>
     *
     * <code>repeated int64 authorIds = 11;</code>
     * @param index The index of the element to return.
     * @return The authorIds at the given index.
     */
    public long getAuthorIds(int index) {
      return authorIds_.getLong(index);
    }
    private int authorIdsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      for (int i = 0; i < genres_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, genres_.getRaw(i));
      }
      if (publishedAt_ != null) {
        output.writeMessage(4, getPublishedAt());
      }
      if (!getPublisherBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, publisher_);
      }
      if (totalPages_ != 0) {
        output.writeInt32(6, totalPages_);
      }
      for (int i = 0; i < categories_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, categories_.getRaw(i));
      }
      if (!getLanguageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, language_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, description_);
      }
      if (!getImageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, image_);
      }
      if (getAuthorIdsList().size() > 0) {
        output.writeUInt32NoTag(90);
        output.writeUInt32NoTag(authorIdsMemoizedSerializedSize);
      }
      for (int i = 0; i < authorIds_.size(); i++) {
        output.writeInt64NoTag(authorIds_.getLong(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < genres_.size(); i++) {
          dataSize += computeStringSizeNoTag(genres_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getGenresList().size();
      }
      if (publishedAt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPublishedAt());
      }
      if (!getPublisherBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, publisher_);
      }
      if (totalPages_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, totalPages_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < categories_.size(); i++) {
          dataSize += computeStringSizeNoTag(categories_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getCategoriesList().size();
      }
      if (!getLanguageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, language_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, description_);
      }
      if (!getImageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, image_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < authorIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(authorIds_.getLong(i));
        }
        size += dataSize;
        if (!getAuthorIdsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        authorIdsMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.ebook_searching.proto.Event.AddBookEvent)) {
        return super.equals(obj);
      }
      org.ebook_searching.proto.Event.AddBookEvent other = (org.ebook_searching.proto.Event.AddBookEvent) obj;

      if (getId()
          != other.getId()) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getGenresList()
          .equals(other.getGenresList())) return false;
      if (hasPublishedAt() != other.hasPublishedAt()) return false;
      if (hasPublishedAt()) {
        if (!getPublishedAt()
            .equals(other.getPublishedAt())) return false;
      }
      if (!getPublisher()
          .equals(other.getPublisher())) return false;
      if (getTotalPages()
          != other.getTotalPages()) return false;
      if (!getCategoriesList()
          .equals(other.getCategoriesList())) return false;
      if (!getLanguage()
          .equals(other.getLanguage())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getImage()
          .equals(other.getImage())) return false;
      if (!getAuthorIdsList()
          .equals(other.getAuthorIdsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      if (getGenresCount() > 0) {
        hash = (37 * hash) + GENRES_FIELD_NUMBER;
        hash = (53 * hash) + getGenresList().hashCode();
      }
      if (hasPublishedAt()) {
        hash = (37 * hash) + PUBLISHED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getPublishedAt().hashCode();
      }
      hash = (37 * hash) + PUBLISHER_FIELD_NUMBER;
      hash = (53 * hash) + getPublisher().hashCode();
      hash = (37 * hash) + TOTAL_PAGES_FIELD_NUMBER;
      hash = (53 * hash) + getTotalPages();
      if (getCategoriesCount() > 0) {
        hash = (37 * hash) + CATEGORIES_FIELD_NUMBER;
        hash = (53 * hash) + getCategoriesList().hashCode();
      }
      hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + getLanguage().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImage().hashCode();
      if (getAuthorIdsCount() > 0) {
        hash = (37 * hash) + AUTHORIDS_FIELD_NUMBER;
        hash = (53 * hash) + getAuthorIdsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ebook_searching.proto.Event.AddBookEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.ebook_searching.proto.Event.AddBookEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Book Ingestion Event message definition
     * </pre>
     *
     * Protobuf type {@code org.ebook_searching.proto.AddBookEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.ebook_searching.proto.AddBookEvent)
        org.ebook_searching.proto.Event.AddBookEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ebook_searching.proto.Event.internal_static_org_ebook_searching_proto_AddBookEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ebook_searching.proto.Event.internal_static_org_ebook_searching_proto_AddBookEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.ebook_searching.proto.Event.AddBookEvent.class, org.ebook_searching.proto.Event.AddBookEvent.Builder.class);
      }

      // Construct using org.ebook_searching.proto.Event.AddBookEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        title_ = "";

        genres_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (publishedAtBuilder_ == null) {
          publishedAt_ = null;
        } else {
          publishedAt_ = null;
          publishedAtBuilder_ = null;
        }
        publisher_ = "";

        totalPages_ = 0;

        categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        language_ = "";

        description_ = "";

        image_ = "";

        authorIds_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ebook_searching.proto.Event.internal_static_org_ebook_searching_proto_AddBookEvent_descriptor;
      }

      @java.lang.Override
      public org.ebook_searching.proto.Event.AddBookEvent getDefaultInstanceForType() {
        return org.ebook_searching.proto.Event.AddBookEvent.getDefaultInstance();
      }

      @java.lang.Override
      public org.ebook_searching.proto.Event.AddBookEvent build() {
        org.ebook_searching.proto.Event.AddBookEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.ebook_searching.proto.Event.AddBookEvent buildPartial() {
        org.ebook_searching.proto.Event.AddBookEvent result = new org.ebook_searching.proto.Event.AddBookEvent(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.title_ = title_;
        if (((bitField0_ & 0x00000001) != 0)) {
          genres_ = genres_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.genres_ = genres_;
        if (publishedAtBuilder_ == null) {
          result.publishedAt_ = publishedAt_;
        } else {
          result.publishedAt_ = publishedAtBuilder_.build();
        }
        result.publisher_ = publisher_;
        result.totalPages_ = totalPages_;
        if (((bitField0_ & 0x00000002) != 0)) {
          categories_ = categories_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.categories_ = categories_;
        result.language_ = language_;
        result.description_ = description_;
        result.image_ = image_;
        if (((bitField0_ & 0x00000004) != 0)) {
          authorIds_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.authorIds_ = authorIds_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ebook_searching.proto.Event.AddBookEvent) {
          return mergeFrom((org.ebook_searching.proto.Event.AddBookEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.ebook_searching.proto.Event.AddBookEvent other) {
        if (other == org.ebook_searching.proto.Event.AddBookEvent.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.genres_.isEmpty()) {
          if (genres_.isEmpty()) {
            genres_ = other.genres_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureGenresIsMutable();
            genres_.addAll(other.genres_);
          }
          onChanged();
        }
        if (other.hasPublishedAt()) {
          mergePublishedAt(other.getPublishedAt());
        }
        if (!other.getPublisher().isEmpty()) {
          publisher_ = other.publisher_;
          onChanged();
        }
        if (other.getTotalPages() != 0) {
          setTotalPages(other.getTotalPages());
        }
        if (!other.categories_.isEmpty()) {
          if (categories_.isEmpty()) {
            categories_ = other.categories_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureCategoriesIsMutable();
            categories_.addAll(other.categories_);
          }
          onChanged();
        }
        if (!other.getLanguage().isEmpty()) {
          language_ = other.language_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (!other.getImage().isEmpty()) {
          image_ = other.image_;
          onChanged();
        }
        if (!other.authorIds_.isEmpty()) {
          if (authorIds_.isEmpty()) {
            authorIds_ = other.authorIds_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAuthorIdsIsMutable();
            authorIds_.addAll(other.authorIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.ebook_searching.proto.Event.AddBookEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.ebook_searching.proto.Event.AddBookEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <pre>
       * The ID of the book
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * The ID of the book
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The ID of the book
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <pre>
       * The title of the book
       * </pre>
       *
       * <code>string title = 2;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The title of the book
       * </pre>
       *
       * <code>string title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The title of the book
       * </pre>
       *
       * <code>string title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The title of the book
       * </pre>
       *
       * <code>string title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The title of the book
       * </pre>
       *
       * <code>string title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList genres_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureGenresIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          genres_ = new com.google.protobuf.LazyStringArrayList(genres_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * List of genres of the book
       * </pre>
       *
       * <code>repeated string genres = 3;</code>
       * @return A list containing the genres.
       */
      public com.google.protobuf.ProtocolStringList
          getGenresList() {
        return genres_.getUnmodifiableView();
      }
      /**
       * <pre>
       * List of genres of the book
       * </pre>
       *
       * <code>repeated string genres = 3;</code>
       * @return The count of genres.
       */
      public int getGenresCount() {
        return genres_.size();
      }
      /**
       * <pre>
       * List of genres of the book
       * </pre>
       *
       * <code>repeated string genres = 3;</code>
       * @param index The index of the element to return.
       * @return The genres at the given index.
       */
      public java.lang.String getGenres(int index) {
        return genres_.get(index);
      }
      /**
       * <pre>
       * List of genres of the book
       * </pre>
       *
       * <code>repeated string genres = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the genres at the given index.
       */
      public com.google.protobuf.ByteString
          getGenresBytes(int index) {
        return genres_.getByteString(index);
      }
      /**
       * <pre>
       * List of genres of the book
       * </pre>
       *
       * <code>repeated string genres = 3;</code>
       * @param index The index to set the value at.
       * @param value The genres to set.
       * @return This builder for chaining.
       */
      public Builder setGenres(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGenresIsMutable();
        genres_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of genres of the book
       * </pre>
       *
       * <code>repeated string genres = 3;</code>
       * @param value The genres to add.
       * @return This builder for chaining.
       */
      public Builder addGenres(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGenresIsMutable();
        genres_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of genres of the book
       * </pre>
       *
       * <code>repeated string genres = 3;</code>
       * @param values The genres to add.
       * @return This builder for chaining.
       */
      public Builder addAllGenres(
          java.lang.Iterable<java.lang.String> values) {
        ensureGenresIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, genres_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of genres of the book
       * </pre>
       *
       * <code>repeated string genres = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGenres() {
        genres_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of genres of the book
       * </pre>
       *
       * <code>repeated string genres = 3;</code>
       * @param value The bytes of the genres to add.
       * @return This builder for chaining.
       */
      public Builder addGenresBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureGenresIsMutable();
        genres_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp publishedAt_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> publishedAtBuilder_;
      /**
       * <pre>
       * The date the book was published
       * </pre>
       *
       * <code>.google.protobuf.Timestamp published_at = 4;</code>
       * @return Whether the publishedAt field is set.
       */
      public boolean hasPublishedAt() {
        return publishedAtBuilder_ != null || publishedAt_ != null;
      }
      /**
       * <pre>
       * The date the book was published
       * </pre>
       *
       * <code>.google.protobuf.Timestamp published_at = 4;</code>
       * @return The publishedAt.
       */
      public com.google.protobuf.Timestamp getPublishedAt() {
        if (publishedAtBuilder_ == null) {
          return publishedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : publishedAt_;
        } else {
          return publishedAtBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The date the book was published
       * </pre>
       *
       * <code>.google.protobuf.Timestamp published_at = 4;</code>
       */
      public Builder setPublishedAt(com.google.protobuf.Timestamp value) {
        if (publishedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          publishedAt_ = value;
          onChanged();
        } else {
          publishedAtBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * The date the book was published
       * </pre>
       *
       * <code>.google.protobuf.Timestamp published_at = 4;</code>
       */
      public Builder setPublishedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (publishedAtBuilder_ == null) {
          publishedAt_ = builderForValue.build();
          onChanged();
        } else {
          publishedAtBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * The date the book was published
       * </pre>
       *
       * <code>.google.protobuf.Timestamp published_at = 4;</code>
       */
      public Builder mergePublishedAt(com.google.protobuf.Timestamp value) {
        if (publishedAtBuilder_ == null) {
          if (publishedAt_ != null) {
            publishedAt_ =
              com.google.protobuf.Timestamp.newBuilder(publishedAt_).mergeFrom(value).buildPartial();
          } else {
            publishedAt_ = value;
          }
          onChanged();
        } else {
          publishedAtBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * The date the book was published
       * </pre>
       *
       * <code>.google.protobuf.Timestamp published_at = 4;</code>
       */
      public Builder clearPublishedAt() {
        if (publishedAtBuilder_ == null) {
          publishedAt_ = null;
          onChanged();
        } else {
          publishedAt_ = null;
          publishedAtBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * The date the book was published
       * </pre>
       *
       * <code>.google.protobuf.Timestamp published_at = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getPublishedAtBuilder() {
        
        onChanged();
        return getPublishedAtFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The date the book was published
       * </pre>
       *
       * <code>.google.protobuf.Timestamp published_at = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getPublishedAtOrBuilder() {
        if (publishedAtBuilder_ != null) {
          return publishedAtBuilder_.getMessageOrBuilder();
        } else {
          return publishedAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : publishedAt_;
        }
      }
      /**
       * <pre>
       * The date the book was published
       * </pre>
       *
       * <code>.google.protobuf.Timestamp published_at = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getPublishedAtFieldBuilder() {
        if (publishedAtBuilder_ == null) {
          publishedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getPublishedAt(),
                  getParentForChildren(),
                  isClean());
          publishedAt_ = null;
        }
        return publishedAtBuilder_;
      }

      private java.lang.Object publisher_ = "";
      /**
       * <pre>
       * The publisher of the book
       * </pre>
       *
       * <code>string publisher = 5;</code>
       * @return The publisher.
       */
      public java.lang.String getPublisher() {
        java.lang.Object ref = publisher_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          publisher_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The publisher of the book
       * </pre>
       *
       * <code>string publisher = 5;</code>
       * @return The bytes for publisher.
       */
      public com.google.protobuf.ByteString
          getPublisherBytes() {
        java.lang.Object ref = publisher_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          publisher_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The publisher of the book
       * </pre>
       *
       * <code>string publisher = 5;</code>
       * @param value The publisher to set.
       * @return This builder for chaining.
       */
      public Builder setPublisher(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publisher_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The publisher of the book
       * </pre>
       *
       * <code>string publisher = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPublisher() {
        
        publisher_ = getDefaultInstance().getPublisher();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The publisher of the book
       * </pre>
       *
       * <code>string publisher = 5;</code>
       * @param value The bytes for publisher to set.
       * @return This builder for chaining.
       */
      public Builder setPublisherBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        publisher_ = value;
        onChanged();
        return this;
      }

      private int totalPages_ ;
      /**
       * <pre>
       * Total pages in the book
       * </pre>
       *
       * <code>int32 total_pages = 6;</code>
       * @return The totalPages.
       */
      @java.lang.Override
      public int getTotalPages() {
        return totalPages_;
      }
      /**
       * <pre>
       * Total pages in the book
       * </pre>
       *
       * <code>int32 total_pages = 6;</code>
       * @param value The totalPages to set.
       * @return This builder for chaining.
       */
      public Builder setTotalPages(int value) {
        
        totalPages_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Total pages in the book
       * </pre>
       *
       * <code>int32 total_pages = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalPages() {
        
        totalPages_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCategoriesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          categories_ = new com.google.protobuf.LazyStringArrayList(categories_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       * List of categories the book belongs to
       * </pre>
       *
       * <code>repeated string categories = 7;</code>
       * @return A list containing the categories.
       */
      public com.google.protobuf.ProtocolStringList
          getCategoriesList() {
        return categories_.getUnmodifiableView();
      }
      /**
       * <pre>
       * List of categories the book belongs to
       * </pre>
       *
       * <code>repeated string categories = 7;</code>
       * @return The count of categories.
       */
      public int getCategoriesCount() {
        return categories_.size();
      }
      /**
       * <pre>
       * List of categories the book belongs to
       * </pre>
       *
       * <code>repeated string categories = 7;</code>
       * @param index The index of the element to return.
       * @return The categories at the given index.
       */
      public java.lang.String getCategories(int index) {
        return categories_.get(index);
      }
      /**
       * <pre>
       * List of categories the book belongs to
       * </pre>
       *
       * <code>repeated string categories = 7;</code>
       * @param index The index of the value to return.
       * @return The bytes of the categories at the given index.
       */
      public com.google.protobuf.ByteString
          getCategoriesBytes(int index) {
        return categories_.getByteString(index);
      }
      /**
       * <pre>
       * List of categories the book belongs to
       * </pre>
       *
       * <code>repeated string categories = 7;</code>
       * @param index The index to set the value at.
       * @param value The categories to set.
       * @return This builder for chaining.
       */
      public Builder setCategories(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCategoriesIsMutable();
        categories_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of categories the book belongs to
       * </pre>
       *
       * <code>repeated string categories = 7;</code>
       * @param value The categories to add.
       * @return This builder for chaining.
       */
      public Builder addCategories(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCategoriesIsMutable();
        categories_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of categories the book belongs to
       * </pre>
       *
       * <code>repeated string categories = 7;</code>
       * @param values The categories to add.
       * @return This builder for chaining.
       */
      public Builder addAllCategories(
          java.lang.Iterable<java.lang.String> values) {
        ensureCategoriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, categories_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of categories the book belongs to
       * </pre>
       *
       * <code>repeated string categories = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCategories() {
        categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of categories the book belongs to
       * </pre>
       *
       * <code>repeated string categories = 7;</code>
       * @param value The bytes of the categories to add.
       * @return This builder for chaining.
       */
      public Builder addCategoriesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureCategoriesIsMutable();
        categories_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object language_ = "";
      /**
       * <pre>
       * The language of the book
       * </pre>
       *
       * <code>string language = 8;</code>
       * @return The language.
       */
      public java.lang.String getLanguage() {
        java.lang.Object ref = language_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          language_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The language of the book
       * </pre>
       *
       * <code>string language = 8;</code>
       * @return The bytes for language.
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        java.lang.Object ref = language_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          language_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The language of the book
       * </pre>
       *
       * <code>string language = 8;</code>
       * @param value The language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        language_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The language of the book
       * </pre>
       *
       * <code>string language = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearLanguage() {
        
        language_ = getDefaultInstance().getLanguage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The language of the book
       * </pre>
       *
       * <code>string language = 8;</code>
       * @param value The bytes for language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        language_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <pre>
       * The description of the book
       * </pre>
       *
       * <code>string description = 9;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The description of the book
       * </pre>
       *
       * <code>string description = 9;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The description of the book
       * </pre>
       *
       * <code>string description = 9;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The description of the book
       * </pre>
       *
       * <code>string description = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The description of the book
       * </pre>
       *
       * <code>string description = 9;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object image_ = "";
      /**
       * <pre>
       * The image of the book (Base64 or URL)
       * </pre>
       *
       * <code>string image = 10;</code>
       * @return The image.
       */
      public java.lang.String getImage() {
        java.lang.Object ref = image_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          image_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The image of the book (Base64 or URL)
       * </pre>
       *
       * <code>string image = 10;</code>
       * @return The bytes for image.
       */
      public com.google.protobuf.ByteString
          getImageBytes() {
        java.lang.Object ref = image_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          image_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The image of the book (Base64 or URL)
       * </pre>
       *
       * <code>string image = 10;</code>
       * @param value The image to set.
       * @return This builder for chaining.
       */
      public Builder setImage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        image_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The image of the book (Base64 or URL)
       * </pre>
       *
       * <code>string image = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearImage() {
        
        image_ = getDefaultInstance().getImage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The image of the book (Base64 or URL)
       * </pre>
       *
       * <code>string image = 10;</code>
       * @param value The bytes for image to set.
       * @return This builder for chaining.
       */
      public Builder setImageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        image_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.LongList authorIds_ = emptyLongList();
      private void ensureAuthorIdsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          authorIds_ = mutableCopy(authorIds_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       * List of author details
       * </pre>
       *
       * <code>repeated int64 authorIds = 11;</code>
       * @return A list containing the authorIds.
       */
      public java.util.List<java.lang.Long>
          getAuthorIdsList() {
        return ((bitField0_ & 0x00000004) != 0) ?
                 java.util.Collections.unmodifiableList(authorIds_) : authorIds_;
      }
      /**
       * <pre>
       * List of author details
       * </pre>
       *
       * <code>repeated int64 authorIds = 11;</code>
       * @return The count of authorIds.
       */
      public int getAuthorIdsCount() {
        return authorIds_.size();
      }
      /**
       * <pre>
       * List of author details
       * </pre>
       *
       * <code>repeated int64 authorIds = 11;</code>
       * @param index The index of the element to return.
       * @return The authorIds at the given index.
       */
      public long getAuthorIds(int index) {
        return authorIds_.getLong(index);
      }
      /**
       * <pre>
       * List of author details
       * </pre>
       *
       * <code>repeated int64 authorIds = 11;</code>
       * @param index The index to set the value at.
       * @param value The authorIds to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorIds(
          int index, long value) {
        ensureAuthorIdsIsMutable();
        authorIds_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of author details
       * </pre>
       *
       * <code>repeated int64 authorIds = 11;</code>
       * @param value The authorIds to add.
       * @return This builder for chaining.
       */
      public Builder addAuthorIds(long value) {
        ensureAuthorIdsIsMutable();
        authorIds_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of author details
       * </pre>
       *
       * <code>repeated int64 authorIds = 11;</code>
       * @param values The authorIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllAuthorIds(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureAuthorIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, authorIds_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of author details
       * </pre>
       *
       * <code>repeated int64 authorIds = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorIds() {
        authorIds_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.ebook_searching.proto.AddBookEvent)
    }

    // @@protoc_insertion_point(class_scope:org.ebook_searching.proto.AddBookEvent)
    private static final org.ebook_searching.proto.Event.AddBookEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.ebook_searching.proto.Event.AddBookEvent();
    }

    public static org.ebook_searching.proto.Event.AddBookEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddBookEvent>
        PARSER = new com.google.protobuf.AbstractParser<AddBookEvent>() {
      @java.lang.Override
      public AddBookEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddBookEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddBookEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddBookEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.ebook_searching.proto.Event.AddBookEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ebook_searching_proto_AddBookEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_ebook_searching_proto_AddBookEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013event.proto\022\031org.ebook_searching.proto" +
      "\032\037google/protobuf/timestamp.proto\"\360\001\n\014Ad" +
      "dBookEvent\022\n\n\002id\030\001 \001(\003\022\r\n\005title\030\002 \001(\t\022\016\n" +
      "\006genres\030\003 \003(\t\0220\n\014published_at\030\004 \001(\0132\032.go" +
      "ogle.protobuf.Timestamp\022\021\n\tpublisher\030\005 \001" +
      "(\t\022\023\n\013total_pages\030\006 \001(\005\022\022\n\ncategories\030\007 " +
      "\003(\t\022\020\n\010language\030\010 \001(\t\022\023\n\013description\030\t \001" +
      "(\t\022\r\n\005image\030\n \001(\t\022\021\n\tauthorIds\030\013 \003(\003B\036Z\034" +
      "github.com/tqchu/SharedProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_org_ebook_searching_proto_AddBookEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_ebook_searching_proto_AddBookEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_ebook_searching_proto_AddBookEvent_descriptor,
        new java.lang.String[] { "Id", "Title", "Genres", "PublishedAt", "Publisher", "TotalPages", "Categories", "Language", "Description", "Image", "AuthorIds", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
